language: php

php:
  - '5.6'

services:
  - mongodb

env:
  - CI_VERSION=3.1.2

branches:
  only:
    - unitesting

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

before_install:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget https://github.com/bcit-ci/CodeIgniter/archive/$CI_VERSION.tar.gz -O - | tar xz
  - cp -r application/* CodeIgniter-$CI_VERSION/application/

# install this project on top of it
install:
  - pwd
  - ls -l
  - cp -r CodeIgniter-$CI_VERSION/application/* application/
  - mv CodeIgniter-$CI_VERSION/system ./
  - mv CodeIgniter-$CI_VERSION/index.php index.php
  - rm -rf CodeIgniter-$CI_VERSION
  - ls -l
  - pwd
  - cd application/tests

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

script:
  - phpunit -c phpunit.xml   #custom test command to make sure CLI args don't break the test